### ISSUE TITLE
Code for calculating NMI

### ISSUE THREAD

**Issue by suvaansh** [nttcslab/Generalized-Domain-Adaptation#1]
Can you please share the code for the calculation of the NMI curves in figure 4 of the paper?

**Comment by Yu-Mitsuzumi** [comment]
Thank you for your interest in our work.

We calculate the NMI of the estimated domain labels in `domain_estimation_ssl/clustering.py`. Please check the code.
If you want to calculate the NMI for the results of different grid sizes, please modify the YAML file in the config directory.

**Comment by suvaansh** [comment]
Thank you for you response.
